import React, { useState } from 'react';
import { AlertTriangle, ShieldCheck, Info, X } from 'lucide-react';

export const MedicalDisclaimerBanner: React.FC = () => {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <div className="bg-amber-950/80 border-b border-amber-500/30 px-4 py-1.5 flex items-center justify-between text-xs text-amber-200">
        <div className="flex items-center space-x-2">
          <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
          <span className="font-semibold text-amber-300">
            RESEARCH & EDUCATIONAL PROTOTYPE:
          </span>
          <span className="text-amber-200/90 hidden sm:inline">
            Not for clinical diagnostic use. AI observations must be interpreted in conjunction with comprehensive histopathological examination.
          </span>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="flex items-center space-x-1 px-2 py-0.5 rounded bg-amber-900/60 hover:bg-amber-800/80 text-amber-300 transition-colors border border-amber-700/50"
        >
          <Info className="w-3.5 h-3.5" />
          <span>Safety Notice</span>
        </button>
      </div>

      {showModal && (
        <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-700 rounded-xl max-w-lg w-full p-6 shadow-2xl space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center space-x-2 text-amber-400">
                <ShieldCheck className="w-6 h-6" />
                <h2 className="text-lg font-bold text-slate-100">Medical Device & Safety Disclaimer</h2>
              </div>
              <button
                onClick={() => setShowModal(false)}
                className="text-slate-400 hover:text-slate-200 p-1 rounded-lg hover:bg-slate-800"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-sm text-slate-300 leading-relaxed max-h-96 overflow-y-auto pr-1">
              <div className="p-3 bg-amber-950/40 border border-amber-500/30 rounded-lg text-amber-200">
                <p className="font-semibold mb-1">Strict Research and Educational Use Only</p>
                <p className="text-xs text-amber-300/90">
                  This software is an investigational AI prototype developed for computational pathology research and educational demonstration in Oral Potentially Malignant Disorders (OPMD) and Oral Squamous Cell Carcinoma (OSCC).
                </p>
              </div>

              <p>
                <strong>1. No Clinical Diagnostic Claims:</strong> The morphological measurements, feature classifications, and segmentation boundaries generated by this application are algorithmic estimates and do not constitute a clinical, medical, or pathological diagnosis.
              </p>
              <p>
                <strong>2. Scope of Observation:</strong> A single cellular feature (such as nuclear hyperchromasia, enlargement, or pleomorphism) cannot establish malignancy in isolation without comprehensive review of full tissue architectural stratification, basement membrane integrity, and clinical correlation.
              </p>
              <p>
                <strong>3. Model Status Transparency:</strong> Only AI models with validated weights report <span className="text-emerald-400 font-mono font-semibold">READY</span>. Models without configured weights report <span className="text-amber-400 font-mono font-semibold">NOT CONFIGURED</span> and do not generate fabricated outputs.
              </p>
            </div>

            <div className="pt-2 flex justify-end">
              <button
                onClick={() => setShowModal(false)}
                className="px-4 py-2 bg-medical-600 hover:bg-medical-500 text-white text-sm font-medium rounded-lg transition-colors"
              >
                I Understand and Acknowledge
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};
